"""Initial schema with pgvector support

Revision ID: 4ae3ce5535a2
Revises: 
Create Date: 2026-01-27 09:17:13.573456+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '4ae3ce5535a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_bodies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regulation_documents',
    sa.Column('compliance_body_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['compliance_body_id'], ['compliance_bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regulation_body_version', 'regulation_documents', ['compliance_body_id', 'version'], unique=False)
    op.create_table('uploaded_documents',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('compliance_body_id', sa.Integer(), nullable=False),
    sa.Column('compliance_section', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('redraft_mode', sa.String(length=50), nullable=False),
    sa.Column('output_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['compliance_body_id'], ['compliance_bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_status', 'uploaded_documents', ['status'], unique=False)
    op.create_table('document_elements',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_docai_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_hierarchy', 'document_elements', ['document_id', 'parent_id'], unique=False)
    op.create_index('idx_doc_order', 'document_elements', ['document_id', 'page_number', 'order_index'], unique=False)
    op.create_table('regulation_texts',
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('section_ref', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_v2', Vector(768), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_embedding_vector', 'regulation_texts', ['embedding_v2'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100})
    op.create_index('idx_regulation_section', 'regulation_texts', ['regulation_id', 'section_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_regulation_section', table_name='regulation_texts')
    op.drop_index('idx_embedding_vector', table_name='regulation_texts', postgresql_using='ivfflat', postgresql_with={'lists': 100})
    op.drop_table('regulation_texts')
    op.drop_index('idx_doc_order', table_name='document_elements')
    op.drop_index('idx_doc_hierarchy', table_name='document_elements')
    op.drop_table('document_elements')
    op.drop_index('idx_document_status', table_name='uploaded_documents')
    op.drop_table('uploaded_documents')
    op.drop_index('idx_regulation_body_version', table_name='regulation_documents')
    op.drop_table('regulation_documents')
    op.drop_table('compliance_bodies')
    # ### end Alembic commands ###
