"""
Prompts package
"""
from app.prompts.templates import (
    ANALYSIS_SYSTEM_PROMPT,
    TABLE_ANALYSIS_PROMPT,
    FORM_VALIDATION_PROMPT,
    LIST_ANALYSIS_PROMPT,
    CONTENT_ANALYSIS_PROMPT,
    REDRAFT_PROMPT,
    QUALITY_SCORE_PROMPT,
    VERIFICATION_PROMPT,
    REPORT_SYNTHESIS_PROMPT,
    get_analysis_prompt
)

__all__ = [
    "ANALYSIS_SYSTEM_PROMPT",
    "TABLE_ANALYSIS_PROMPT",
    "FORM_VALIDATION_PROMPT",
    "LIST_ANALYSIS_PROMPT",
    "CONTENT_ANALYSIS_PROMPT",
    "REDRAFT_PROMPT",
    "QUALITY_SCORE_PROMPT",
    "VERIFICATION_PROMPT",
    "REPORT_SYNTHESIS_PROMPT",
    "get_analysis_prompt",
]
